### ISSUE TITLE
Which API Version ?

### ISSUE THREAD

**Issue by lakshsyal123** [phpclassic/php-shopify#100]
Hello @tareqtms 

Which API version is used "2019-04" or "2019-07" ?

**Comment by richardklint** [comment]
Use 2019-04.

2019-07 isn't fully supported yet due to [cursor based pagination](https://help.shopify.com/en/api/guides/paginated-rest-results).

**Comment by lakshsyal123** [comment]
Okay once it will be done... I need to update my composer and that's it ? 

Or I need to do any further modifications?

**Comment by tareqtms** [comment]
@richardklint 
By default, we are using `2019-04` (as of v1.1.2) and you can replace it by giving `'ApiVersion'` in config array.

**Comment by lakshsyal123** [comment]
Cool :)
