### ISSUE TITLE
Discount code 'lookup' not available?

### ISSUE THREAD

**Issue by louiswalch** [phpclassic/php-shopify#107]
I think there may be an error in the DiscountCode resource. Shopify defines a DiscountCode as a child of PriceRule in all cases except one - when "looking up" a PriceRule by it's discount code. You can see this here:
https://help.shopify.com/en/api/reference/discounts/discountcode#lookup-2019-07

There is no way with the current framework to do a `lookup` as it always errors, unless I'm doing it wrong.

    DiscountCode is a child resource of PriceRule. Cannot be accessed directly.

**Comment by tareqtms** [comment]
@louiswalch 
This is missed from our side, will fix in the next release. Thanks

**Comment by louiswalch** [comment]
Thanks for looking into it so quickly. I did some testing and it seems to be implemented weird and difficult to use.

- If called with a code that doesn't exist, it throws a `PHPShopify\Exception\ApiException` with 404 Not Found.

- If called with a code that does exist, it throws a `PHPShopify\Exception\CurlException` with Request failed with HTTP Code 303.

It would be nice if it rather returned `false` or the PriceRule.
