### ISSUE TITLE
Update an order (PUT Request) not work for me

### ISSUE THREAD

**Issue by trantuanngoctn97** [phpclassic/php-shopify#110]
Hi guys, 
i use an example **Update an order (PUT Request)** on the ReadMe page to update `fulfillment_status` of an order. But its not work, `fulfillment_status` not change.

This is my code 
````
$updateInfo = array (
    "fulfillment_status" => "fulfilled",
);        
$orders = $this->shopify->Order($order_id)->put($updateInfo);
````
- Please help me, how can i update field `fulfillment_status` of an order?

And can i update fulfillments field by using method put ?
I want to update tracking_number in fulfillments field of an order. I use postman for test. 
````
$updateInfo = array (
    "tracking_number" => "1157431066720-1",
);  
$this->shopify->Order($order_id)->Fulfillment->post($updateInfo);
````
In the first call, its work. fulfillments  field has data with `tracking_number` same i update. But in the second call, its say `order - is already fulfilled` . 
If i use `$this->shopify->Order($order_id)->Fulfillment->put($updateInfo);` Its say: 
````
Type: PHPShopify\Exception\CurlException
Message: Request failed with HTTP Code 406.
````

Can i update fulfillments field by using method put ? Please help me how to update a fulfillments ?

Thank you in advance.

**Comment by tareqtms** [comment]
@trantuanngoctn97 
It doesn't seem like the issue is related to this SDK. It might be from Shopify side. Can you please do a try using Postman or any similar tool? Let us know again if you are able to do it with Postman and only failing with our PHP SDK.

**Comment by trantuanngoctn97** [comment]
I used Postman and got this issue. Do you need any more infomation?

**Comment by tareqtms** [comment]
That means, the issue is not related to this SDK. Please ask in the [Shopify community](https://community.shopify.com/c/Shopify-Community/ct-p/en) for more help on this.

**Comment by trantuanngoctn97** [comment]
Yeah i will. 
How can i update fulfillments by this SDK ?

**Comment by tareqtms** [comment]
This one you used was the correct format:

`$this->shopify->Order($order_id)->Fulfillment->put($updateInfo);`

**Comment by trantuanngoctn97** [comment]
Ya, and it not work now. 
I see Shopify support multiple tracking_number in **fulfillments** . How should i do to add multiple tracking_number in **fulfillments** with the SDK?

**Comment by tareqtms** [comment]
This is only a wrapper library, if shopify supports anything, you will be able to do it with the same way they allow, see the library documentation to transform your query into our SDK format. If you need more help please create a new issue with the specific case. I will check on that later. Thanks.

**Comment by trantuanngoctn97** [comment]
yeah, thank you for your help.

**Comment by hmaesta** [comment]
@trantuanngoctn97 Did you manage to do this?
Even the example code doesn't work for me.

```php
$updateInfo = array (
    "fulfillment_status" => "fulfilled",
);

$shopify->Order($orderID)->put($updateInfo);
```

**Comment by SebastienPoncelet** [comment]
You cannot update directly the "fulfillment_status". Had this issue previously and it's because Shopify doesn't allow you to do it that way.

The "fulfillment_status" will update itself automatically when you actually fulfill some of the order's line items by providing the following:

- tracking_number -> have to provide it even if you don't have it. If it's missing then clearly set it at "null" or your POST won't work.
- line_items -> provide their IDs if not all of them are fulfilled + the associated quantity.

With this POST, Shopify will detect the corresponding status, whether the order is fulfilled, or partially or something else. The "fulfillment_status" will therefore be updated following this.

Hope it helps.

**Comment by natanrufino** [comment]
> You cannot update directly the "fulfillment_status". Had this issue previously and it's because Shopify doesn't allow you to do it that way.
> 
> The "fulfillment_status" will update itself automatically when you actually fulfill some of the order's line items by providing the following:
> 
> * tracking_number -> have to provide it even if you don't have it. If it's missing then clearly set it at "null" or your POST won't work.
> * line_items -> provide their IDs if not all of them are fulfilled + the associated quantity.
> 
> With this POST, Shopify will detect the corresponding status, whether the order is fulfilled, or partially or something else. The "fulfillment_status" will therefore be updated following this.
> 
> Hope it helps.



> You cannot update directly the "fulfillment_status". Had this issue previously and it's because Shopify doesn't allow you to do it that way.
> 
> The "fulfillment_status" will update itself automatically when you actually fulfill some of the order's line items by providing the following:
> 
> * tracking_number -> have to provide it even if you don't have it. If it's missing then clearly set it at "null" or your POST won't work.
> * line_items -> provide their IDs if not all of them are fulfilled + the associated quantity.
> 
> With this POST, Shopify will detect the corresponding status, whether the order is fulfilled, or partially or something else. The "fulfillment_status" will therefore be updated following this.
> 
> Hope it helps.

Thank you very much. That's a very important thing to know.
