### ISSUE TITLE
 Is it possible to get Variants of a product(using GET request)

### ISSUE THREAD

**Issue by divyasunil** [phpclassic/php-shopify#12]
The child resources can be used in a nested way.
For example, get the images of a product (GET request)
$productID = 23564666666;
$productImages = $shopify->Product($productID)->Image->get();

Is it possible to get Variants of a product(using GET request) like above????

**Comment by KiloooNL** [comment]
Yes, use the following code below. The data is returned in a multi-dimensional array.

```
$productID = 23564666666;
$productDetails = $shopify->Product($productID)->get();

// Print the array. You will see all the available information displayed.
print_r($productDetails);
```

**Comment by tareqtms** [comment]
Please try the same way:
```
$productID = 23564666666;
$productVariants = $shopify->Product($productID)->Variant->get();
```
