### ISSUE TITLE
Static config? Why?

### ISSUE THREAD

**Issue by andreisusanu** [phpclassic/php-shopify#128]
I have the following scenario:

20 workers, working in parallel, processing Shopify API calls.
More than 10 Shopify stores are connected.

This sets the API credentials statically, and is used in a global way.
PHPShopify\ShopifySDK::config($config);

Worker 1: Setting config for shop #1. Making the API call.
Worker 2: Setting config for shop #2. Making the API call.

The configs are mixed up.
That is bad... bad bad bad!

**Comment by tareqtms** [comment]
@andreisusanu 
Sorry, I understand your problem and the reason for frustration. We already had a discussion on this and we were supposed to make this change. But unfortunately, I am unable to give enough time to the project at the moment which delays everything. If you have the solution in mind, you can help with a pull request. Again sorry for your inconvenience.
