### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by theMadScientist007** [phpclassic/php-shopify#13]
When using $connection->Discount()->get()the following error
`
Fatal error: Uncaught PHPShopify\Exception\ApiException: Scope undefined for API access: discounts_next. Valid scopes: admin_notifications, analytics, apps, capital, channel_app, channels, checkout_settings, checkouts, collection_listings, collection_publications, content, customers, disputes, draft_orders, fulfillments, gift_card_adjustments, gift_cards, home, images, inventory, locations, marketing_events, meta_tags, mobile_payments, mobile_platform_applications, notifications, online_store, online_store_preferences, orders, payment_gateways, price_rules, product_engagements, product_listings, product_publications, products, reports, resource_feedbacks, script_tags, scripts, shipping, shopify_payments, social_network_accounts, taxes, themes, tracking_pixels, and users in /home/cognizancerpm/public_html/vendor/php-shopify-master/lib/ShopifyResource.php:432 Stack trace: #0 /home/cognizancerpm/public_html/vendor/php-shopify-master/lib/ShopifyResource.php(274): PHPShopify\ShopifyResource->processResponse(Array, 'discounts') in `

Is there a specific call that needs to be made in order to access the discount codes list?

**Comment by KiloooNL** [comment]
When you create your initial AuthRequest, you need to include the scopes.
It would be something like this:

`        $config = array(
            'ShopUrl' => 'YOUR_SHOP_URL',
            'ApiKey' => 'YOUR_API_KEY',
            'SharedSecret' => 'YOUR_SHARED_SECRET',
        );

        PHPShopify\ShopifySDK::config($config);

        // Include scopes. 
        $scopes = 'read_products,write_products,read_script_tags,write_script_tags,read_shipping, **discounts_next**';
        $redirectUrl = 'YOUR_REDIRECT_URL';

        \PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);
        PHPShopify\ShopifySDK::config($config);
        $accessToken = \PHPShopify\AuthHelper::getAccessToken();
        // print the access token or save to a file or something`
