### ISSUE TITLE
Order Tags Not working

### ISSUE THREAD

**Issue by balazaigo** [phpclassic/php-shopify#132]
Hi I wanna query for the orders which it contains tags such as 'xyz' But unfortunately it is getting me all orders instead of the orders which are containing the tags. 

I'm having orders which containing tags 'xyz' is 3 But instead of 3 it is providing me all 50 orders. Can anyone please let me know and resolve this issue?

**Comment by tareqtms** [comment]
@balazaigo 
Unfortunately, Shopify doesn't provide the option for searching with tags through the REST API. Here you can find the statement and a workaround:
https://community.shopify.com/c/Shopify-APIs-SDKs/REST-API-Orders-tags-field-used-for-filtering-and-searching/m-p/567763
