### ISSUE TITLE
Create new product with image in one request.

### ISSUE THREAD

**Issue by geetpurwar** [phpclassic/php-shopify#135]
I am using this code, but this doesn't add image.
It creates product but without image.

`$productArray = [
		'title' => 'My New Product',
        'body_html' => 'My New Product Description',
        'vendor'=> 'My Product Vendor',
        'product_type'=> 'My Product Type',
        'published'=> true,
        'images' => [
        	'image' => [
	        	'src' => 'https://www.maridonmarketing.com/wp-content/uploads/2018/08/maridon-marketing.png'
	        ]
        ],
        'published_scope'=> 'web',
        'variants' => array(
            array(
            	'option1' => 'Default',
                'price' => '100.00',
                'sku' => 'ABC123',
                'inventory_quantity'=> '1',
                'inventory_management' => 'shopify',
                'taxable' => true,
                'requires_shipping' => true
            )
        )
	];`

**Comment by geetpurwar** [comment]
Figured it out.

**Comment by javimata** [comment]
Could you share the solution?
