### ISSUE TITLE
How to do create multiple options for new product.

### ISSUE THREAD

**Issue by usFox** [phpclassic/php-shopify#141]
I have a question. I can create multiple options for the new product.  Just one option "1 PC", How can I do? Thank you!

`<?php 
require_once('../php-shopify/vendor/autoload.php');

date_default_timezone_set("America/Los_Angeles");

$product = new Shopify_PRODUCT();
$product->add_product();

class Shopify_PRODUCT {
    private $shopify;

    public function __construct(){
        $config = array(
            'ShopUrl' => '',
            'ApiKey' => '',
            'Password' => '',
        );
        $this->shopify = new PHPShopify\ShopifySDK($config);
    }

    function add_product() {
        $variants = array();
        $variant_data = array (
            "title" => "2 PC / 0.5mm",
            "price" => "22.00",
            "sku" => "abc",
            "compare_at_price" => "23.00",
            "taxable" => true,
            "barcode" => "123121",
            "weight" => "0.2",
            "weight_unit" => "lb",
            "inventory_quantity" => 30,
            "option1" => "2 PC",
            "option2" => "0.5mm"
        );

        $option_data1 = array(
            'name' => "Pack",
            'position' => 1,
            'values' => array("1 PC", "2 PC")
        );

        $option_data2 = array(
            'name' => "Size",
            'position' => 2,
            'values' => array("0.5mm", "0.7mm")
        );

        $options = array($option_data1, $option_data2);

        array_push($variants, $variant_data);

        $product = array (
            "title" => "test product",
            "body_html" => "test product",
            "vendor" => "GOOD",
            "product_type" => "Pen",
            "tags" => "test product",
            "published" => false,
            "variants" => $variants,
            "option" => $options
        );

        var_dump($product);
        $result = $this->shopify->Product->post($product);
    }

}`

**Comment by tareqtms** [comment]
@usFox 
You didn't mention clearly what issue you are getting with your codes. Btw, I see your code is fine except that you used wrong key for the options, it should be `options` in place of `option`. 
```php
        "options" => $options
```
