### ISSUE TITLE
CSP error after calling \PHPShopify\AuthHelper::createAuthRequest()

### ISSUE THREAD

**Issue by webserviceXXL** [phpclassic/php-shopify#147]
I'm not sure if this is the right place, but it seems that in some cases there is en error with the Content Security Policy after calling createAuthRequest().

`\PHPShopify\AuthHelper::createAuthRequest(SCOPES, $redirectUrl);`

If I comment out the line, the app loads as expected. Of course without customer data as I cannot request an AccessToken, but the layout and design is displayed normally within the Shopify UI.

What else?

- This only happens in Firefox not in Chrome.
- The app runs as embedded app.

I also already tried to add a CSP to the AuthHelper class, but didn't worked too. Any ideas?

**Comment by lakshsyal123** [comment]
@webserviceXXL : Received the same problem a few days ago, I contacted Shopify Support, basically this is a problem with their end they need to resolve it. Hopefully, you need to do the same.

**Comment by dasDaniel** [comment]
do you have any more info on this? Seems like they're saying that it's an issue with Firefox redirecting the child window instead of the parent window, and referencing this article: https://shopify.dev/tools/embedded-app-sdk/oauth

**Comment by lakshsyal123** [comment]
Would you like to share your App login page URL, I recently resolved this issue. I could check if you got the same error.

**Comment by webserviceXXL** [comment]
@lakshsyal123 Thanks for your offer. In the meantime I was able to fix the problem, too. Although the EASDK is already deprecated there is an frame breaker snippet available to do the auth process in the parent window. 

https://shopify.dev/tools/embedded-app-sdk/oauth

**Comment by lakshsyal123** [comment]
Got it you can post your solution here so that if any other person sees this post could get an answer. Also, mark it as closed

**Comment by webserviceXXL** [comment]
@lakshsyal123 I used the snippet from the documentation above. So for me this is solved. But I would say it's still an issue of the framework. Everyone who is using php-shopify and has an embedded app will have the same problem in Firefox and Safari.

**Comment by tareqtms** [comment]
@lakshsyal123 
As I see Shopify says:
>  Embedded App SDK is deprecated. Use Shopify App Bridge instead.
I don't think it should be wise to spend time on this issue. I will close the issue as "wont fix", but you are always welcome to send a PR, if you have a ready solution and happy to share with others.
