### ISSUE TITLE
Undefined index: ApiUrl

### ISSUE THREAD

**Issue by bruceviljoen** [phpclassic/php-shopify#151]
I've updated and double checked the my settings in ShopifySDK.php
--------------------------------------------------------------
$config = array(
    'ShopUrl' => 'yourshop.myshopify.com',
    'ApiKey' => '***YOUR-PRIVATE-API-KEY***',
    'Password' => '***YOUR-PRIVATE-API-PASSWORD***',
);
--------------------------------------------------------------

I can't get rid of this error:
--------------------------------------------------------------
Notice: Undefined index: ApiUrl in C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\ShopifyResource.php on line 145

Fatal error: Uncaught PHPShopify\Exception\CurlException: 6 : Could not resolve host: products.json in C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\CurlRequest.php:173 Stack trace: #0 C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\CurlRequest.php(84): PHPShopify\CurlRequest::processRequest(Resource id #1) #1 C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\HttpRequestJson.php(71): PHPShopify\CurlRequest::get('products.json', Array) #2 C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\ShopifyResource.php(337): PHPShopify\HttpRequestJson::get('products.json', Array) #3 C:\inetpub\wwwroot\Shopify\php-shopify-master\index.php(8): PHPShopify\ShopifyResource->get() #4 {main} thrown in C:\inetpub\wwwroot\Shopify\php-shopify-master\lib\CurlRequest.php on line 173

**Comment by tareqtms** [comment]
Please show your full code (except the ApiKey / Password).

**Comment by bruceviljoen** [comment]
<?php
echo "Composer - Test Page Load";

include("vendor/autoload.php");
$shopify = new PHPShopify\ShopifySDK;
$products = $shopify->Product->get();
?>

**Comment by bruceviljoen** [comment]
echo "Composer - Test Page Load";

include("vendor/autoload.php");
$shopify = new PHPShopify\ShopifySDK;
$products = $shopify->Product->get();

**Comment by tareqtms** [comment]
You didn't apply to config to ShopifySDK. It should be like :

```php
echo "Composer - Test Page Load";

include("vendor/autoload.php");
$shopify = new PHPShopify\ShopifySDK($config);
$products = $shopify->Product->get();
```
