### ISSUE TITLE
Cancel a fulfillment

### ISSUE THREAD

**Issue by centraleffects** [phpclassic/php-shopify#160]
Hi Everyone,

It would be of great help if we can cancel a fulfillment too.
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentorder?api[version]=2020-04#cancel-2020-04

> PHPShopify \ Exception \ SdkException
Child Resource Cancel is not available for Fulfillment

`$cancellation = (new Shopify())->Order($orderID)->Fulfillment($fulfillmentID)->Cancel()->post([
        "fulfillment_order" =>  [
		    "id" =>  $fulfillmentID,
		    "order_id" =>  $orderID,
		    "request_status" =>  "submitted",
		    "status" =>  "open",
		    "supported_actions" =>  [
		      "cancel_fulfillment_order"
		    ]
		]
    ])`

Thanks!

**Comment by tareqtms** [comment]
@centraleffects 
It's already available as a custom functions. (See the custom functions section in README for details.)
```php
$shopify->Order($orderID)->Fulfillment($fulfillmentID)->cancel();
```
