### ISSUE TITLE
Cannot seem to fulfil orders

### ISSUE THREAD

**Issue by guerrillacontra** [phpclassic/php-shopify#163]
I am trying to fulfil an order and it seems to be ok as I get a 200 OK status, but on the shopify store it remains Unfulfilled.

```
$data = [
            'fulfillment' => [
                'location_id' => $location_id,
                'tracking_number'=> null,
                'line_items'=>$lineItems
            ],
            "notify_customer" =>true
        ];

      $shopify->Order($orderid)->Fulfillment->post($data);
```

Here is what $data looks like as a json snapshot:

```
{
    "fulfillment": {
        "location_id": 18162909233,
        "tracking_number": null,
        "line_items": [
            {
                "id": 4829140910129,
                "quantity": 1
            }
        ]
    },
    "notify_customer": true
}
```
What am I doing wrong?

**Comment by tareqtms** [comment]
@guerrillacontra 
You have only created a fulfillment, but did not complete. You need to get the fulfillment id then call `$shopify->Order($orderid)->Fulfillment($id)->complete()`

**Comment by guerrillacontra** [comment]
Thank you for the very quick response,

I just checked the body response hat was 200 OK as noticed:

{"error":"location_id must be specified when creating fulfillments."}

But I am including a location_id in the data, and I have checked my stores locations and the id matches what I am sending as an integer. :/

**Comment by tareqtms** [comment]
@guerrillacontra 
Ok, the problem here is you are putting key `fulfillment` inside. The data should get inside the `data` array. the resource key is handled by the SDK. So it should be like:
```php
$data = [
    'location_id' => $location_id,
     'tracking_number'=> null,
     'line_items'=>$lineItems,
    "notify_customer" =>true,
];
```

**Comment by guerrillacontra** [comment]
Thank you @tareqtms you are a big help, that worked perfectly :)
