### ISSUE TITLE
Fulfillment Issue-  HTTP Code 406

### ISSUE THREAD

**Issue by centraleffects** [phpclassic/php-shopify#164]
I am trying to fulfill an order with the following : 

```
$fulfillments = (new Shopify())->Order({OrderID})->Fulfillment()->put([
	    	'line_items' => [
	    		['id' => '{line_item_id}']
	    	],
	    	'location_id' =>  {location_id},
	    	'tracking_number' => '{tracking_number}',
	        'tracking_urls' => [
	            "https://{tracking_urls}"
	        ],
	        'notify_customer' => false
    ]);
```

Result:
`Request failed with HTTP Code 406.`

Thank you in advance.

**Comment by tareqtms** [comment]
You need to provide the Fulfillment ID  to get the Fulfillment resource, before calling the put method. Here:

```php
(new Shopify())->Order({OrderID})->Fulfillment({FulfillmentID})->put(
```

**Comment by threedytotal** [comment]
I was struggling with this even using @tareqtms 's answer, but this worked for me eventually when I wanted to release a held fulfilment:-

`$fulfilment_order = $shopify->Order($shopify_order_id)->FulfillmentOrder()->get()[0];
$id = $fulfilment_order['id'];
$shopify->FulfillmentOrder($id)->release_hold();
`

Hope this helps anyone else struggling with this error code.
