### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by duqkefly** [phpclassic/php-shopify#168]
Hi friends..

Can u help m with this issue:

--> Fatal error: Uncaught PHPShopify\Exception\CurlException: 60 : SSL certificate problem: unable to get local issuer certificate in C:\wamp64\www\getshopify2\vendor\phpclassic\php-shopify\lib\CurlRequest.php on line 173
![shopify_issue1](https://user-images.githubusercontent.com/17454473/86279458-a7f0ed00-bb9f-11ea-98c6-16bac26ca822.png)

**Comment by tareqtms** [comment]
The problem is with the curl setup of your PHP installation. Please check here for a possible solution : https://stackoverflow.com/a/31830614/5645769. If not please search in Google or Stackoverflow. This is not related to this package.

**Comment by duqkefly** [comment]
Thank u.
It works fine!
