### ISSUE TITLE
Deleting Script Tag

### ISSUE THREAD

**Issue by sjranjan** [phpclassic/php-shopify#169]
i was able to create script tag as follows...

$shopify->ScriptTag->post(array('src' => 'URL', 'event' => 'onload'));

Since i executed it many times the file is being loaded several times (many script tags added). Now am trying to delete it. But unable to do so. I read script tags as follows...
$result = $shopify->ScriptTag->get(array('src' => 'URL'));
and i got all script tags in array... Then i tried deleting it in following ways...

$shopify->ScriptTag->delete(SCRIPT_TAG_ID);
$shopify->ScriptTag->delete(array('id' =>SCRIPT_TAG_ID));
$shopify->ScriptTag->delete(array('script_tag_id' =>SCRIPT_TAG_ID));

nothing works... all fails with result " Request failed with HTTP Code 406. "

how to delete script tag ?

**Comment by tareqtms** [comment]
Try this:

```php
$shopify->ScriptTag(SCRIPT_TAG_ID)->delete();
```
