### ISSUE TITLE
The ProductListing resource is not available

### ISSUE THREAD

**Issue by dixitvelocity** [phpclassic/php-shopify#17]
I am building a Shopify Sales Channel.

I have added the **ProductListing** resource in ShopifySDK. 'ProductListing' resource added to ShopifySDK.php

Following code added to ProductListing.php and saved into libraries :
namespace PHPShopify
class ProductListing extends ShopifyResource
{
    /**
     * @inheritDoc
     */
    public $resourceKey = 'product_listing';
}

https://help.shopify.com/api/reference/productlisting

I think you should update the code.

**Comment by tareqtms** [comment]
Thank you for the update, I will add it soon. You can send me a pull request if you have a fork with the added file.

**Comment by debuss** [comment]
It is not fixed.
You need to add ProductListing in ShopifySDK.php as well !
(In header @property-read @method and $resources)

```php
/**
 * ...
 * @property-read Product $Product
 * @property-read ProductVariant $ProductVariant
 * @property-read ProductListing $ProductListing
 *
 * ...
 * @method Product Product(integer $id = null)
 * @method ProductVariant ProductVariant(integer $id = null)
 * @method ProductListing ProductListing(integer $id = null)
 */
class ShopifySDK
{
    /**
     * List of available resources which can be called from this client
     *
     * @var string[]
     */
    protected $resources = array(
        // ...,
        'Product',
        'ProductVariant',
        'ProductListing',
       // ...
    );
}
```
