### ISSUE TITLE
"Search is not available" for Orders and Product

### ISSUE THREAD

**Issue by doctea** [phpclassic/php-shopify#172]
I'm starting to experiment with Shopify for an upcoming migration and I'm finding that I can't use the 'search' method to search for Orders and Products against my Shopify development store.  I receive the message "Search is not available for Orders".  I seem to be able to search for Customers without any issue.  

I'm quite new to Shopify, so I'm not sure if this is expected behaviour, or where I'd find information about this in the documentation?

If this isn't possible with the Shopify API, am I right thinking that the "standard" workaround is to fetch all of the respective data from Shopify in advance, cache it in a local database and search that instead?

Thanks

**Comment by tareqtms** [comment]
If you are getting such a response, that should be Shopify itself not providing the option. Please post in the Shopify community ask support. Thanks.
