### ISSUE TITLE
All of a sudden getting a curl_init() error

### ISSUE THREAD

**Issue by skillmatic-co** [phpclassic/php-shopify#173]
> PHP Fatal error:  Uncaught Error: Call to undefined function PHPShopify\\curl_init() in /var/www/example.com/www/vendor/phpclassic/php-shopify/lib/CurlRequest.php:49

Have any breaking changes been made to this library recently?

Seems to be stemming from this line:

```
$products = $shopify->Product()->get($params);
```

Where my `$params` variable looks like this:

```
$params = array(
  'ids' => implode(', ', $productIDs),
  'fields' => 'id,title,handle,vendor,price,images,tags,variants'
);
```

**Comment by skillmatic-co** [comment]
Ah, I think I see my issue. I'm also using Phusion Passenger for another site on my server. Passenger uses libcurl3, and this library uses libcurl4. I'm going to have to try to solve this one.

**Comment by skillmatic-co** [comment]
Can someone confirm that this library cannot use libcurl3 and must use libcurl4?

**Comment by tareqtms** [comment]
There is no such version limit, any libcurl should work.

**Comment by skillmatic-co** [comment]
> There is no such version limit, any libcurl should work.

Weird, then my original issue still stands. Any idea what could be causing this error?

**Comment by skillmatic-co** [comment]
I resolved my issue with Passenger and it fixed my issue.

**Comment by cd-ali-ehsan** [comment]
How did you resolve it? What are the steps? 
I am having the exact same issue.
