### ISSUE TITLE
How Can I get a Variant of one product

### ISSUE THREAD

**Issue by duqkefly** [phpclassic/php-shopify#174]
$variant = $spf->ProductVariant(########);

Hi friends.,

I need all variants of a specific product.

but,

This code is returning me the same all time when I pass any diferent parameter.!
 what is bad in this statement.

**Comment by tareqtms** [comment]
It should be like this:
```php
$variant = $spf->Product(####)->Variant()->get();
```

**Comment by duqkefly** [comment]
thanks...
