### ISSUE TITLE
Minor Issue: 'Refund->calculate()' does not support code completion in PHPStorm.

### ISSUE THREAD

**Issue by howard-mintus** [phpclassic/php-shopify#189]
The custom action `Refund->calculate()` does not support code completion due to improper documentation. 

**File in Interest:** `vendor/phpclassic/php-shopify/lib/Refund.php`
```php
/**
 * --------------------------------------------------------------------------
 * Refund -> Custom actions
 * --------------------------------------------------------------------------
 * @method array calculate()      Calculate a Refund.
 *
 */
class Refund extends ShopifyResource
{
    /**
     * @inheritDoc
     */
    protected $resourceKey = 'refund';

    /**
     * @inheritDoc
     */
    protected $customPostActions = array (
        'calculate',
    );
}
```

**Problematic Area:**
```php
/**
 * --------------------------------------------------------------------------
 * Refund -> Custom actions
 * --------------------------------------------------------------------------
 * @method array calculate()      Calculate a Refund.
 *
 */
```

**How to Fix:**
Change the documentation as follows. It will allow PHPStorm to recognize that the method `calculate()` requires a parameter.
```php
/**
 * --------------------------------------------------------------------------
 * Refund -> Custom actions
 * --------------------------------------------------------------------------
 * @method array calculate(array $config)      Calculate a Refund.
 *
 */
```

**Comment by tareqtms** [comment]
@howard-mintus 
I appreciate your time to find the issue and provide a possible fix. I would suggest you to send a pull request with the mentioned changes, so that we get your contribution counted. Thanks.

**Comment by howard-mintus** [comment]
@tareqtms 

Pull request has been made for your review. Please review the change and merge it if there is no need for additional work. Thanks.
