### ISSUE TITLE
Update this library to PHP7.2 and PHPUnit 8.5

### ISSUE THREAD

**Issue by bambamboole** [phpclassic/php-shopify#193]
Hey guys,

Pretty nice work  you've done so far with this library. Thanks a lot.

The setup itself is a bit old, thats why I ask if you would accept a PR which updates the library to php 7.2 and phpunit 8.5.

This gives us the option to use return types to harden the code more.

**Comment by tareqtms** [comment]
Thanks @bambamboole 
I will do it as early as possible. (Hopefully during the next weekends. )

**Comment by bambamboole** [comment]
@tareqtms just post here if you need some help.

**Comment by tareqtms** [comment]
@bambamboole 
Sorry for the delay. But I couldn't find the pull request you mentioned about. All the recent pull requests are already merged now. ( I am checking with the travis issue before creating a new release though).

**Comment by bambamboole** [comment]
@tareqtms I did not put effort in, because I first wanted your go. 

But then I will start on this today :)

**Comment by tareqtms** [comment]
@bambamboole 
Great. Will be waiting for it. Thanks in advance.

**Comment by bambamboole** [comment]
Ok, the current test setup seems not to work.
Is there some kind of setup needed to get them workin?

**Comment by tareqtms** [comment]
You will need to have 3 env variables: 
```bash
SHOPIFY_SHOP_URL,
SHOPIFY_API_KEY,
SHOPIFY_API_PASSWORD
```
See here how it's being used while preparing the test environment : https://github.com/phpclassic/php-shopify/blob/master/tests/TestResource.php#L22
