### ISSUE TITLE
Unable to Use

### ISSUE THREAD

**Issue by mIlanvivacity** [phpclassic/php-shopify#2]
Hello,
Greetings!

Getting issue in using this library, getting error "Fatal error: Class 'PHPShopify\TestSimpleResource' not found", please guide what I am missing.

Looking forward for your help.

Thanks & Regards
Milan G.

**Comment by tareqtms** [comment]
Hi Milan,

Glad that you are using my library.

TestSimpleResource class should be available only in test mode (autoload-dev). Can you please share your file or code to see how you are implementing it?

Thanks,

Tareq Mahmood

**Comment by mIlanvivacity** [comment]
Hello Tareq

Thanks for quick reply!

I am trying to access to the file like http://localhost/phpshopify/tests/BlogTest.php and it is giving me an error Fatal error: Class 'PHPShopify\TestSimpleResource' not found in /opt/lampp/htdocs/phpshopify/tests/BlogTest.php on line 12
Haven't added any custom code yet

Thanks & Regards
Milan G.

**Comment by tareqtms** [comment]
Hi Milan,

That won’t work that way actually. You need a composer, composer.json to define the library and php script which will include the vendor/autoload.php file. Then you can call BlogTest class from the php file. 

If you still want it without composer, you need to create a custom file and include all necessary class files manually. Like :

include ‘phpshopfiy/tests/TestSimpleResource.php’
include ‘phpshopfiy/tests/BlogTest.php’

Thanks,

Tareq Mahmood

**Comment by mIlanvivacity** [comment]
Hello Tareq

I have composer.json but still didn't figured out how to use it

**Comment by mIlanvivacity** [comment]
Hello Tareq

I hope these screenshots will help you for guiding me, I ran the command to download the package and this is what I got, please see screenshots
![screenshot from 2017-07-26 15 00 18](https://user-images.githubusercontent.com/30437003/28614407-5ce11f8e-7213-11e7-8405-6a2b5d96bd21.png)
![screenshot from 2017-07-26 15 00 25](https://user-images.githubusercontent.com/30437003/28614406-5ce10404-7213-11e7-8919-0938f9a393fd.png)

Looking forward for your reply.

Thanks & Regards
Milan G.

**Comment by tareqtms** [comment]
HI,

Try putting this php file same folder (shopifywp) and modify as per your need.

Thanks,

Tareq Mahmood

**Comment by mIlanvivacity** [comment]
Hello Tareq

I copied the file BlogTest.php to shopifywp 
![screenshot from 2017-07-26 15 26 46](https://user-images.githubusercontent.com/30437003/28615491-ddfb67b6-7216-11e7-8ad7-ffd21a730069.png)
folder and tried to run that file, still got the same error.

**Comment by tareqtms** [comment]
It won’t. It’s not the proper way of doing it. Please follow the file I sent you.

**Comment by mIlanvivacity** [comment]
which file?

**Comment by tareqtms** [comment]
Please check my last emails. I sent you an example php file.

**Comment by mIlanvivacity** [comment]
Sorry, but I can't find any file. can you please send me again. Thanks in advance

**Comment by tareqtms** [comment]
Sorry, I was replying in emails. Not sure, why the file didn't come here. As you closed the ticket, I think the issue is resolved for you. Thank you.

**Comment by mIlanvivacity** [comment]
yes it is, thank you

**Comment by yacineA** [comment]
I have the same issue. What was the solution? What is the right way to work with this sdk, just want to test with the test files

**Comment by tareqtms** [comment]
@yacineA Did you using composer or directly including the files?

**Comment by yacineA** [comment]
Can you send me the php example file ?

**Comment by prashantsachaniya** [comment]
> Can you send me the php example file ?

Hello Tareq,
Can you share me that file or include in repo so everyone can find it easy to use with examples.
Thank you so much
