### ISSUE TITLE
Location of code parameter

### ISSUE THREAD

**Issue by axelf** [phpclassic/php-shopify#201]
Hi,

what is the reason for calling the get-parameter for code in the lib and not passing as an parameter itself? It would be more consistent to pass this param with all other parameters. What if the name is changing? Also it is more readable code whats going on in my script.

**Comment by axelf** [comment]
I was wrong :-)

**Comment by tareqtms** [comment]
@axelf 
I am not sure what class or file you are talking about. Can you please elaborate a bit more with code examples?

**Comment by axelf** [comment]
@tareqtms i mean the file AuthHelper.php Line 168. There is a param for the code-parameter. Wouldn't it be better to pass as a function parameter? It's no criticism only my thoughts. By the way, it is a nice libraray :-)

**Comment by tareqtms** [comment]
@axelf 
No, `$_GET['code']` is the access token we get from Shopify after the authentication process is complete. Shopify send it with the URL parameter.

**Comment by axelf** [comment]
@tareqtms i think `$_GET['code']` is not the access token but the code from shopify and we have to exchange this code for the access_token by making a new request. After making this request we get the access token.

**Comment by tareqtms** [comment]
@axelf 
Yes, you are right with that. However, still it's the same coming from Shopify, so we need to get it from `$_GET['code']` url param. However, we could make it function param, and then you need to get it from url param before calling the function. It's possible to make it an optional parameter in the function without breaking the old functionality. If you can test it out and you find it useful, you can create a pull request yourself. 
Thanks for your idea, btw.

**Comment by axelf** [comment]
@tareqtms will test it.

Could i ask you some more?
I used this lib with my php-app. This app has an index page (list) and details page. On the details page i have no access to the parameter "shop". The src-url of the iframe contains this paramter. Only on index page i have access via $_GET['shop']. Do you know why is that and is there any solution? I need this param on the details page in order to query the database (SELECT access_token where shop = $shop)

**Comment by tareqtms** [comment]
@axelf 
If the info is only in the iframe src-url, then you need to get it from URL params, what's wrong with that?

**Comment by axelf** [comment]
@tareqtms Let's say the src-url of the iframe is `myapp.com/?shop=xy`. Within my app i call `myapp.com/details` then i have no more access to the $_GET-array of the parent iframe

**Comment by tareqtms** [comment]
@axelf 
There might be many ways to solve this. A simple way can be store it in the session variable when you reach `myapp.com/?shop=xy` and when you are in `myapp.com/details` get it back from session variable.

**Comment by axelf** [comment]
@tareqtms yes, you are right :-) If the session expires i will renew. I thougt there was any solution from shopify to handle such situations. So i forgot the session
