### ISSUE TITLE
Getting 302 error response from shopify Api

### ISSUE THREAD

**Issue by ArnaudDx** [phpclassic/php-shopify#206]
Hi
With my team we encountered an issue for shopify customer using another domain than myshopify.com

After some debug we found where the probleme was:
tools/shopifysdk/phpclassic/php-shopify/lib/CurlRequest.php - function init

Add this line 
`curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

**Comment by LaurenciusRay** [comment]
Suggest to save and use myshopify domain to hit API Shopify instead of shop domain.

**Comment by ArnaudDx** [comment]
Hello.
Yes sorry we found it after...

**Comment by csautot** [comment]
Thank you for sharing tip on using the Shopify domain (xxxxxxx.myshopify.com) instead of any custom domain in use to be used with ShopUrl param in $config array. This helped! 

Also, for others, make sure to leave out 'https://' for this value, and just use the .myshopify.com domain.
