### ISSUE TITLE
How can I get the response headers returned from a call to the API?

### ISSUE THREAD

**Issue by DataDeveloped** [phpclassic/php-shopify#208]
As noted in another comment I made here below, I'm getting a 520 response from an API call but I need to see what is in the response headers to follow up with Shopify response and provide e.g. the request ID.

Getting the headers also has useful pagination information in it.

Is there a way in the php-shopify library to return the headers optionall and / or log them?

Thank you!

**Comment by dev-markus** [comment]
have the same question

**Comment by tareqtms** [comment]
You can get it from 
```php
PHPShopify\CurlRequest::$lastHttpResponseHeaders
```

**Comment by eballeste** [comment]
request status code is in the static variable:

```php
PHPShopify\CurlRequest::$lastHttpCode
```
