### ISSUE TITLE
Subresource requests whose URLs contain embedded credentials 

### ISSUE THREAD

**Issue by remiemalik** [phpclassic/php-shopify#21]
Hi,

We have developed a Shopify App with your library.
At the beginning we have created two pages: a landing page where the user grants his/her rights to the shop and a redirect page which displays the information after the app is installed.
So far so good, we got these parts working.
However after installing our App, we browse to our shop and click on the App in particular Chrome.
The page is trying to load our landing page which has the following content:

   $config = array(
        'ShopUrl' => $shop,
        'ApiKey' => $settings->apikey,
        'Password' => $settings->apisecret,
    );
    
    PHPShopify\ShopifySDK::config($config);
    \PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);

In our Chrome browser network tab it displays the following message: Subresource requests whose URLs contain embedded credentials.

The question is, how can we bypass this behaviour? Firefox ignores it and just redirects us to our redirect page, which works fine. Please advice.

Thanks,

Greetings,

Remie

**Comment by remiemalik** [comment]
Not present anymore. 
Found a workaround.

**Comment by binipinki** [comment]
@remiemalik can u share how u solved this

**Comment by remiemalik** [comment]
@binipinki we placed an exit; statement (dirty) after the createAuthRequest call.
That way, it always ends with the request and does not bypass any other function (odd behaviour).
