### ISSUE TITLE
Do we need to upgrade anything related to shopify warring attached

### ISSUE THREAD

**Issue by mshbric** [phpclassic/php-shopify#218]
A developer needs to update private apps before 1 April 2021

**Comment by tareqtms** [comment]
The default API Version was there as `2020-01`. Please upgrade your app to use PHPShopify SDK version v1.1.17 or you can use the custom config variable `ApiVersion` to use the latest API version always.

**Comment by mshbric** [comment]
@tareqtms I think we should update to 2020-04 correct ? or 2020-01 has no difference ?
![Screenshot from 2021-03-21 19-47-33](https://user-images.githubusercontent.com/77699476/111915331-5b777580-8a7e-11eb-9f5e-09bd352bd983.png)

**Comment by tareqtms** [comment]
Go with the latest one,  2021-01 or 2020-10.
