### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by MirFaith** [phpclassic/php-shopify#22]
Fatal error: Uncaught Error: Class 'Php_Shopify_Apps\lib\Product' not found in C:\xampp\htdocs\Php_Shopify_Apps\lib\ShopifySDK.php:206 Stack trace: #0 C:\xampp\htdocs\Php_Shopify_Apps\lib\ShopifySDK.php(174): Php_Shopify_Apps\lib\ShopifySDK->__call('Product', Array) #1 C:\xampp\htdocs\Php_Shopify_Apps\lib\ShopifySDK.php(43): Php_Shopify_Apps\lib\ShopifySDK->__get('Product') #2 {main} thrown in C:\xampp\htdocs\Php_Shopify_Apps\lib\ShopifySDK.php on line 206

**Comment by KiloooNL** [comment]
Can you show the code you're using that triggers this error?

**Comment by tareqtms** [comment]
Closing the issue because of not getting any response from OP. Anyone can re-open the issue if you can recreate the same.
