### ISSUE TITLE
Product->put() issue - HTTP Code 406

### ISSUE THREAD

**Issue by KiloooNL** [phpclassic/php-shopify#23]
Hi @tareqtms,
I'm trying to update an existing product with the API:

Here's the code I'm using:
``$putArray = array("id" => "100000000", "title" => "titleTest", "body_html" => "description");``
``// Update existing product``
``$shopify->Product->put($putArray);``

However, when I process this, I get the following error:

> Fatal error: Uncaught PHPShopify\Exception\CurlException: Request failed with HTTP Code 406. in E:\xampp\htdocs\libraries\php-shopify\lib\ShopifyResource.php:485 Stack trace: #0 E:\xampp\htdocs\libraries\php-shopify\lib\ShopifyResource.php(395): PHPShopify\ShopifyResource->processResponse(NULL, 'product') #1 E:\xampp\htdocs\shopifyInventory.php(146): PHPShopify\ShopifyResource->put(Array) #2 {main} thrown in E:\xampp\htdocs\libraries\php-shopify\lib\ShopifyResource.php on line 485

I can't figure out why it is responding with 'product' being null, as the array elements seem OK and the product does exist. Any advice here?

**Comment by tareqtms** [comment]
Can you please try removing the `id` field from the `$putArray`?

**Comment by tareqtms** [comment]
Actually you might need something like this:
```
$productID = 100000000;
$putArray = array("title" => "titleTest", "body_html" => "description");
$shopify->Product(100000000)->put($putArray);
```

**Comment by KiloooNL** [comment]
I have tried that, it gives me the same error. According to the Shopify API, when updating a product using PUT, an ID needs to be specified. I will try your example now and let you know how I go.

**Comment by tareqtms** [comment]
Please see my last comment, you need to specify the ID, in a different way here.

**Comment by KiloooNL** [comment]
Ok I have tried your example. Works perfectly! Thanks :D
