### ISSUE TITLE
Example on the ReadMe to update order status is incorrect

### ISSUE THREAD

**Issue by joeyc002** [phpclassic/php-shopify#25]
The example is:

```
$updateInfo = array (
    "fulfillment_status" => "fulfilled",
);

$shopify->Order($orderID)->put($order);
```

I'd assume it should be:

```
$updateInfo = array (
    "fulfillment_status" => "fulfilled",
);

$shopify->Order($orderID)->put($updateInfo);

```

However Shopify still just returns order information as if it is a GET request.

**Comment by joeyc002** [comment]
I don't think Shopify accepts it this way anymore. You have to create a new fulfillment. You can't edit the status directly.

**Comment by remiemalik** [comment]
Hi Joeyc,

I figured out the same way to create a Fullfulment.
Can you tell me what location_id should be?
Not sure what to specify there.

Kind regards,

Remie
