### ISSUE TITLE
Unable to generate access token

### ISSUE THREAD

**Issue by Aditya-php** [phpclassic/php-shopify#256]
Unable to generate the access token if i use  API credentials of custom app. So please let me know that how does it possible.

**Comment by tareqtms** [comment]
You can use the Password as your access token for private apps.

**Comment by Aditya-php** [comment]
Please see the below sample code.

$config = array(
'ShopUrl' => '<>',
'ApiKey' => dd5f6, //example
'Password' =>'shpss_a50ea62f8',  //example
);
$obj= new ShopifySDK($config);

It's is working correct for private App but getting 'invalid access token' error in Custom App

**Comment by Aditya-php** [comment]
@tareqtms : can you please help on this.

**Comment by anikghosh256** [comment]
@Aditya-php  

[How to get the permanent access token for a shop ](https://github.com/phpclassic/php-shopify#how-to-get-the-permanent-access-token-for-a-shop)

are you following this steps for you custom app?
