### ISSUE TITLE
composer require phpclassic/php-shopify

### ISSUE THREAD

**Issue by flyfish01** [phpclassic/php-shopify#26]
when i excute composer require phpclassic/php-shopify, report below exception: 

[ReflectionException]
 Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist

 [ErrorException]
 Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::whatProvides(Composer\DependencyResolver\Pool $pool, $name) should b
 e compatible with Composer\Repository\ComposerRepository::whatProvides(Composer\DependencyResolver\Pool $pool, $name, $bypassFilters = false)

**Comment by tareqtms** [comment]
Hi @flyfish01 This issue is not related to this library. Please follow this stackoverflow question and answers : https://stackoverflow.com/questions/36437837/composer-throws-reflectionexception-class-fxp-composer-assetplugin-repository

**Comment by tareqtms** [comment]
Closing the issue because of not getting any response from OP. Anyone can re-open the issue if you can recreate the same.
