### ISSUE TITLE
Adding  a tag in shopify customer (post method not working). I use this code

### ISSUE THREAD

**Issue by KomalDeveloper01** [phpclassic/php-shopify#270]
$getPara ="1234567890";
 $data = array('tags' => 'sales_agent');
 $shopify->Customer($getPara)->post($data);

**Comment by nVuln** [comment]
post for create, use `put` method when you need update a resource
```php
$shopify->Customer($getPara)->put($data);
```

see: https://shopify.dev/api/admin-rest/2022-07/resources/customer#put-customers-customer-id
