### ISSUE TITLE
so How to create a fulfillment in the latest api version?

### ISSUE THREAD

**Issue by shadowhenry** [phpclassic/php-shopify#272]
I'm confused now. could someone give an example?

**Comment by guerrillacontra** [comment]
I am also stuck, no matter what I put in the body it simply won't work AND permissions are set up correctly on the store.

**Comment by nVuln** [comment]
see: https://shopify.dev/api/admin-rest/2022-07/resources/fulfillment#post-fulfillments
```php
$client->Fulfillment->post([
    'fulfillment' => [
        'message' => 'The package was shipped this morning.',
        'notify_customer' => false,
        'tracking_info' => [
            'number' => 'tracking number 1'
        ],
        'line_items_by_fulfillment_order' => [
            [
                'fulfillment_order_id' => '1046000811'
            ]
        ]
    ]
]);
```

need plugin v1.2.2 to work

**Comment by shadowhenry** [comment]
The latest version couldn't be pulled by composer, so I choose to assign the default api version: "2022-04", then I success to create.
