### ISSUE TITLE
Fulflillments 2022-10 endpoint support and SDK's versioning upgrade release?  

### ISSUE THREAD

**Issue by maricicmilos** [phpclassic/php-shopify#277]
Dear sir @tareqtms, when would repository be updated with support for "Creates a fulfillment for one or many fulfillment orders" [https://shopify.dev/api/admin-rest/2022-10/resources/fulfillment#post-fulfillments]? 
Any info on versioning upgrade and when can be expected for this library package to use 2022-10 as default api reference?
`    /**
     * @var string Default Shopify API version
     */
    public static $defaultApiVersion = '2022-07';`
Or we should use apiVersion $config parametar in future to switch our request to 2022-10? Thank you very much for all your work

**Comment by tareqtms** [comment]
@maricicmilos 
It is recommended that you use the `$config` parameter to control which Api Version you use. Default Api Version is only kept as a fallback. However, I will update the default one soon. Anyways, thanks for reminding me.

**Comment by maricicmilos** [comment]
@tareqtms Thank you for your reply. I have found eventually everything I need. Cheers!
