### ISSUE TITLE
Fulfillment is a child resource of Order. Cannot be accessed directly.

### ISSUE THREAD

**Issue by shaikharbaz2** [phpclassic/php-shopify#287]
i am not able to fulfill shopify order i am using phpclassic/php-shopify": "1.2.0 version 

$result =$shopify->Fulfillment($fulfillmentId)->update_tracking([
"tracking_number" => '11111',
"tracking_urls" => 'https://tracking_url...',
"notify_customer" => true,
"location_id" => $location_id
]);

**Comment by tareqtms** [comment]
Please check the latest release
