### ISSUE TITLE
Endpoint for fulfillment_orders on order

### ISSUE THREAD

**Issue by Coennie** [phpclassic/php-shopify#288]
Hi There,
I'm looking for the endpoint to get all fulfillment_orders of an order. 
It should be: https://{{yourstore}}.myshopify.com/admin/orders/{{order_id}}/fulfillment_orders.json which do result in a list of fulfillment_orders when I run it in Postman.
I've seen other tickets about this, but they mention it should be part of the order object under "fulfillments" but that is just empty, so I can't use it.
Any suggestions?
Regards

**Comment by IMPMAC** [comment]
I had a similar issue, you got to add one of these scopes

`'write_assigned_fulfillment_orders', 'write_fulfillments', 'write_merchant_managed_fulfillment_orders', 'write_third_party_fulfillment_orders'`

I am not sure exactly what one, but one of those scopes will cause that object not to be empty

**Comment by Coennie** [comment]
I've added all possible scopes and made a new custom app on the shop, but unfortunately it still remains empty. But no problem, once the mentioned PR is merged I can grab all fulfillmentOrders by that endpoint.
Thanks for your response though!
