### ISSUE TITLE
Accessing AssignedFulfillmentOrder

### ISSUE THREAD

**Issue by Spotnyk** [phpclassic/php-shopify#294]
I'm dreading posting this because I'm sure the answer is simple and obvious. :)

I am unsure how to access `AssignedFulfillmentOrder`. I have looked extensively (code, issues, etc) to find the answer but have not succeeded.

I (incorrectly) assumed, based on the endpoint path it would be `$shopify->AssignedFulfillmentOrder()->get()`.

I then tried (just to be sure):
`$shopify->Order()->AssignedFulfillmentOrder()->get()`
`$shopify->FulfillmentOrder()->AssignedFulfillmentOrder()->get()`
`$shopify->Fulfillment()->AssignedFulfillmentOrder()->get()`
..all which failed.

I found the pull request #278, and while the AssignedFulfillmentOrder docs are linked in that PR, there does not seem to be anything in it specifically to support it.

What am I missing? Thank you in advance.

PS: I do have the proper scopes.

**Comment by Spotnyk** [comment]
I went ahead and made the changes (primarily to check my own sanity that I wasn't missing it) then created a PR (#295).

Hopefully it is acceptable (literally 😉).

**Comment by tareqtms** [comment]
Solved by #278

**Comment by Spotnyk** [comment]
> Solved by #278

Is it? I've looked and looked. Done searches through the entire codebase. If there is a way to access the `AssignedFulfillmentOrder` resource, I have not been able to find it.

**Comment by Spotnyk** [comment]
I see you merged it.

Thank you sir!
