### ISSUE TITLE
Not getting any access tooken

### ISSUE THREAD

**Issue by divyasunil** [phpclassic/php-shopify#3]
Hi,

We trying use this to interact with shopify and get access token

listing the step we followed,

1. ran this 'composer require phpclassic/php-shopify' in cmd(my app)
2. put the code snippet
  $config = array(
    'ShopUrl' => 'yourshop.myshopify.com',
    'ApiKey' => '***YOUR-PRIVATE-API-KEY***',
    'SharedSecret' => '***YOUR-SHARED-SECRET***',
);

PHPShopify\ShopifySDK::config($config);
$scopes = 'read_products,write_products,read_script_tags,write_script_tags';

$redirectUrl = 'https://yourappurl.com/your_redirect_url.php';

\PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);
$accessToken = \PHPShopify\AuthHelper::getAccessToken();

********************************************************************************************************
We are not getting any response .

Is any step we missed??
Please help

**Comment by tareqtms** [comment]
Does the page redirects to the shopify page?

**Comment by tareqtms** [comment]
Did you replace the placeholders properly? Like "yourshop.myshopify.com", "YOUR-PRIVATE-API-KEY" etc., needs to be replaced with your app specific values.

**Comment by divyasunil** [comment]
Yes I have placed the values correctly

please see my code
$config = array(
		  'ShopUrl' => 'claritysub.myshopify.com',
		  'ApiKey' => '213d713ee42ffc90b00173b05697a747',
		  'SharedSecret' => 'a70d45df6719c9de416b4753ca0fcedc',
		);
		
		PHPShopify\ShopifySDK::config($config);
		
		$scopes = 'read_orders,read_products,write_products';
		$redirectUrl = 'https://beta.tallify.in/wp-json/tallify/v1/redirect_uri';
		\PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);

any extra library file need to include?

**Comment by divyasunil** [comment]
through ajax call we are calling this php snippet function.

**Comment by tareqtms** [comment]
Ok. So, I understand the problem now. This cannot be implemented through AJAX call because, there is a redirection process in between. It will redirect the user to his/her shop and he/she needs to give the approval from his/her shopify website. Then it redirects back to the redirect url where you get the access token using `$accessToken = \PHPShopify\AuthHelper::getAccessToken();`

**Comment by tareqtms** [comment]
Please test your url directly instead of the Ajax call and you will understand the process, I believe.

**Comment by divyasunil** [comment]
ok thanks

**Comment by divyasunil** [comment]
can you share any example?
the code we are using is not going to the Shopify authorize URL? That's where we are stuck.

it looks like e are not able to create the authentication request using the code below

`//your_authorize_url.php
$scopes = 'read_products,write_products,read_script_tags,write_script_tags';
//This is also valid
//$scopes = array('read_products','write_products','read_script_tags', 'write_script_tags'); 
$redirectUrl = 'https://yourappurl.com/your_redirect_url.php';

\PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);`

**Comment by tareqtms** [comment]
Did you try manually instead of Ajax call? As I said, Ajax call wont work for this. 
When I visit your link https://beta.tallify.in/wp-json/tallify/v1/redirect_uri, I see it's redirecting to your shop url and asking for password.
