### ISSUE TITLE
does the sdk support the 2024-04 api version?

### ISSUE THREAD

**Issue by gabrielalves00** [phpclassic/php-shopify#328]
![image](https://github.com/phpclassic/php-shopify/assets/168373096/534ff583-3d2f-41a2-b6ee-3d9bbfc6227d)

got this error then changed the api version to 2024-04, do someone is having the same problem?

**Comment by tareqtms** [comment]
You can use the latest API Version by mentioning in the config : 
```php
$config = array(
    'ShopUrl' => 'yourshop.myshopify.com',
    'AccessToken' => '***ACCESS-TOKEN-FOR-THIRD-PARTY-APP***',
    'ApiVersion' => '2024-04',
);
```

**Comment by tareqtms** [comment]
@gabrielalves00 
Anyways, I have updated the default API version in the SDK, so you will be good if you use the latest version of the sdk (v1.2.10). However, it is always recommended to mention your own supported Api Version in your config.
