### ISSUE TITLE
Get value of single asset

### ISSUE THREAD

**Issue by webserviceXXL** [phpclassic/php-shopify#36]
Does this framework supports to get the value of a single asset? The thing is, for assets it different to most of the other calls because Shopify excepts the key for the template as request parameter. Also an Asset do not have an id like an articel in blogs for example.

> To retrieve a single asset, include asset[key]=#{asset_key} as a request parameter. For example, to retrieve the asset with a key of templates/index.liquid, the request might be /admin/themes/828155753/assets.json?asset[key]=templates/index.liquid.

Could find any example in the readme nor in the tests to get the value.

What I already tried:
```
  $template1 = $shopify->Theme($themes[0]['id'])->Asset->get(array('key'=>'sections/page.liquid'));
  $template2 = $shopify->Theme($themes[0]['id'])->Asset('sections/page.liquid')->get();
```

**Comment by shawnhind** [comment]
I'm also trying to figure out how to do this.

**Comment by bartoszarendt** [comment]
You're using invalid syntax guys. There should be an 'asset' and 'theme_id' keys sent in the request like this:

$asset_args = array(
  'asset' => array(
    'key' => 'sections/page.liquid'
  ),
  'theme_id' => $themes[0]['id']
);
$template = $shopify->Theme($themes[0]['id'])->Asset->get($asset_args);

**Comment by tareqtms** [comment]
@webserviceXXL 
Tested and confirmed that @bartoszarendt 's solution is working fine. You need that syntax as Shopify API expects it that way.
