### ISSUE TITLE
Posting to Metafield of Product

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#38]
I get an exception when trying to post to the metafield of a product.

The request I'm doing looks like this:
`$client->Product($this->id)->Metafield->post($payload);`

ID is the ID of the product, payload is an array containing metafield data, the payload was valid when I tested this when posting to the Shop metafield rather than a product one.

Am I doing something wrong or is this a bug?

The exception I get is below:
`PHPShopify\Exception\SdkException thrown with message "Invalid resource name get. Pls check the API Reference to get the appropriate resource name."`

**Comment by tareqtms** [comment]
Can you please show what is your payload?

**Comment by shawnhind** [comment]
Sorry, this can be closed.  The call that was failing was another one which I did make a mistake in.   My bad.
