### ISSUE TITLE
Is it possible to get all products within a given collection?

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#39]
I have a use case where I need to pull a list of products which are in a given collection.  It would be useful to be able to query for this in a similar way to:  $client->Collection($id)->Product->get();

Is anything like this currently possible?  I'm thinking I may have to just do this with http requests from what I'm seeing.

Or alternatively in a way that closer matches the API it could be done like this $client->Product($collection_id)->get(); in order to filter for products that are in that collection.  This is how you do it with their API directly, you pass URL argument for the collection as a filter.

**Comment by tareqtms** [comment]
Closing the issue because of not getting any response from OP. Anyone can re-open the issue if you can recreate the same.
