### ISSUE TITLE
SmartCollection Metafields

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#40]
With the SDK it's currently not possible to add metafields to SmartCollections (from what I can see).

According to this doc page:
https://help.shopify.com/en/api/reference/metafield

It should be possible to add metafields to SmartCollections using the /collections/{id}/metafields.json endpoint.  I've tested using postman and it is indeed possible to add metafields to those objects using the collections resource but I couldn't figure out how to do this with the SDK.  I'm currently using a manual HTTP request to do this call instead.

**Comment by tompec** [comment]
@shawnhind I just PR'd a fix to this https://github.com/phpclassic/php-shopify/pull/43

**Comment by tareqtms** [comment]
Fixed with #43
