### ISSUE TITLE
HMAC value not found in url parameters

### ISSUE THREAD

**Issue by buddyy93** [phpclassic/php-shopify#41]
![capture](https://user-images.githubusercontent.com/22981271/43761477-c2736b46-9a57-11e8-9c69-fd0600e13a71.PNG)

please help, i'm getting this error.
these are my codes.

function index()
    {
        if ($this->isPost()){
            $config = array(
                'ShopUrl'  => preg_replace("(^https?://)", "", $this->input->post('shopify')),
                'ApiKey'   => 'key',
                'SharedSecret' => 'key',
            );
//            $this->addChannel();
            PHPShopify\ShopifySDK::config($config);
            $scopes = 'read_products,write_products,read_orders,write_orders';
            $redirectUrl = 'http://localhost:8080/settings/channels/';
            \PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);
        }
        PHPShopify\ShopifySDK::config($config);
        $accessToken = \PHPShopify\AuthHelper::getAccessToken();
        print_r($accessToken);
}
function addShopify(){
        $this->load->view('settings/shopify');
    }

**Comment by tareqtms** [comment]
Please remove this part from your index function. (This is being run before the request is send to shopify for verificatio,  when HMAC value is not present.) Please use a seperate function and/or URL for this:
```
 PHPShopify\ShopifySDK::config($config);
$accessToken = \PHPShopify\AuthHelper::getAccessToken();
print_r($accessToken);
```
