### ISSUE TITLE
[question] How to fetch products that match a SKU

### ISSUE THREAD

**Issue by str** [phpclassic/php-shopify#42]
How can I get the product/produts filtering by SKU?

**Comment by str** [comment]
BTW, I was able to get it with this URL: `/admin/variants/search.json?query=sku:{$sku}`  but I don't know how to do that via the SDK

**Comment by shawnhind** [comment]
I also ran into some problems with this SDK not being able to provide certain filtering parameters.  I'm not sure that it is possible unless I missed it.  It seems to only allow filtering via ID.

**Comment by diegolamonica** [comment]
Hi @str, it seems that `ProductVariant` class extends `ShoppifyResource` which implements the method `search`.
This method generates exactly the URL as you want: `$shoppify->ProductVariant->search("sku:{$sku}")` and magic should happen.

**Comment by tareqtms** [comment]
@str Pls follow as diegolamonica suggested.

**Comment by vasanthhr** [comment]
@tareqtms @diegolamonica 

I tried this `$shoppify->ProductVariant->search("sku:{$sku}")` but it always gives output as `Uncaught PHPShopify\Exception\ApiException: {"errors":"Not Found"} `even though sku present in inventory

I just tried with to get list of products with belwo APIs then it got list of products :
```
$products = $shopify->Product->get();
 var_dump($products);
```
