### ISSUE TITLE
PHPShopify\Exception\ApiException  : Not Found

### ISSUE THREAD

**Issue by iOliverZH** [phpclassic/php-shopify#53]
> PHPShopify\Exception\ApiException  : Not Found

  at /home/vagrant/code/local/vendor/phpclassic/php-shopify/lib/ShopifyResource.php:496
    492|
    493|         if (isset($responseArray['errors'])) {
    494|             $message = $this->castString($responseArray['errors']);
    495|
  > 496|             throw new ApiException($message);
    497|         }
    498|
    499|         if ($dataKey && isset($responseArray[$dataKey])) {
    500|             return $responseArray[$dataKey];

  Exception trace:

  1   PHPShopify\ShopifyResource::processResponse(["Not Found"], "product")
      /home/vagrant/code/local/vendor/phpclassic/php-shopify/lib/ShopifyResource.php:315

**Comment by iOliverZH** [comment]
When the product has not been found, I get this error message.

**Comment by tareqtms** [comment]
@iOliverZH 
You get the "Not Found" exception, when the product is not found. What is the issue here?

**Comment by tareqtms** [comment]
@iOliverZH 
The exception seems proper. So closing the issue, you can re-open the issue, if you feel there is any issue.

**Comment by tronics** [comment]
I would say it is certainly an issue because it is a fatal error.
So a loop using the examples might ruin a script.

Better implement in the examples:
			try {
			   $result = $shopify->InventoryLevel->set($objStock);
			   print_r($result);
			}
			catch (exception $e) {
				echo $e->getMessage();
			}
