### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by micahelbaz** [phpclassic/php-shopify#54]
Getting this error in my logs today:

ERROR - 2018-11-14 20:43:27 --> Severity: error --> Exception: 7 : Failed to connect to store_name-test.myshopify.com port 443: Connection timed out /home/store_name/public_html/vendor/phpclassic/php-shopify/lib/CurlRequest.php 147

Not sure if its a library issue or if shopify is having issues on their end.

Any insight would be greatly appreciated.

**Comment by shawnhind** [comment]
I've been getting a lot of this lately too.  I'm thinking the issue might be on Shopify's end.  My app was working for a couple of months without ever having that error.  On Friday they changed their whole embedded APP API so I wonder if that may have something to do with it.

Yesterday they posted a status update saying they API was having issues timing out requests but then they said it was resolved an hour later.

**Comment by tareqtms** [comment]
Seems to be a temporary server issue.
