### ISSUE TITLE
Retry loop in curl request logic

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#56]
The SDK includes a while loop that keeps retrying until a 429 is no longer received.  In my case this behaviour is unexpected and undesirable.  My app has many background jobs running for stores and has logic to queue jobs to retry later.  I do not want the processes to sleep for a potentially infinite amount of time.  

I've forked the repo to remove this logic for myself.  I think at the very least this option should be made as a config which can be toggled on or off.  If a config option is desired for this, I'll submit a pull request with that change.

**Comment by tareqtms** [comment]
Please create a pull request with your changes. I will review and merge if that is not harmful to any existing features.

**Comment by shawnhind** [comment]
Right now in my fork I've just removed the retry logic because I don't want this happening in the SDK as I handle it in my queue system.  

Do you want my pull request to have just that logic removed or a config option to enable/disable that when initializing the SDK with the default as enabled.

The problem with doing a while(1) with a break in this case is that if you keep making requests over and over every half a second you aren't allowing your bucket to refill which can cause the request to keep failing and the process to eventually time out.  It's better to implement the retry logic in your app code with some sort of escalating delay or throttling.
