### ISSUE TITLE
how to add script_tag on my store?

### ISSUE THREAD

**Issue by shaileshsitestrokes** [phpclassic/php-shopify#57]
i have try to add script_tag on my store but i am getting error ?

**Comment by shawnhind** [comment]
What error are you getting and how did you try doing it?

**Comment by shaileshsitestrokes** [comment]
Hello,

Thanks for quick replay.
Here is my code to try to post scripttag to my store
$scopes = 'read_products,write_products,read_script_tags,write_script_tags';

$shopify = new PHPShopify\ShopifySDK($config);
$auth = \PHPShopify\AuthHelper::createAuthRequest($scopes, $redirectUrl);


// PHPShopify\ShopifySDK::config($config);
$accessToken = \PHPShopify\AuthHelper::getAccessToken();

Now i am successfully getting accesstoken and also fetching my products using 
$products = $shopify->Product->get();

Now i am unable to post my script to my store 
$config = array(
    'ShopUrl' => 'store.myshopify.com',
    'ApiKey' => '0de028fccdd14837507e6tdyf76e',
    'SharedSecret' => '37a4c8918w6e60b215fdf0177e',
);

$shopify = new PHPShopify\ShopifySDK($config);

$accessToken = \PHPShopify\AuthHelper::getAccessToken();

// echo $accessToken;
// exit;

$config = array(
    'ShopUrl' => 'storename.myshopify.com',
    'AccessToken' => $accessToken,
);

$shopify = new PHPShopify\ShopifySDK($config);
$shopify1 = new PHPShopify\ShopifyResource($config);

$src = "https://mydomain.com/app/jquery.min.js";
$shopify1->post(array("post"), '/admin/script_tags.json', array( "script_tag" => array( "event"=>"onload", "src"=>$src)));

**Comment by shawnhind** [comment]
I've neverused the ShopifyResource object.

This could also be done by posting to $shopify->ScriptTag->post(array)

**Comment by shaileshsitestrokes** [comment]
Hello,

Thanks for the help.
Now its working

**Comment by tareqtms** [comment]
@shaileshsitestrokes Closing the issue since you said it's working now.

**Comment by binipinki** [comment]
can u post full code, we are not able to add script with above code. plz help

**Comment by binipinki** [comment]
@shawnhind  can u plz help in doing this
