### ISSUE TITLE
is it possible to create webhook using this library?

### ISSUE THREAD

**Issue by divyasunil** [phpclassic/php-shopify#6]
is it possible to create webhook using this library?

**Comment by tareqtms** [comment]
Yes!

**Comment by divyasunil** [comment]
please provide the syntax.

**Comment by divyasunil** [comment]
instead of below code which all library functions I need to replace,

>  $user = wp_get_current_user();
> 		  $userID = $user->ID;
> 		  $token = get_user_meta($userID,'shopifyresponse',true);
> 
> 		  $url = 'https://claritysub.myshopify.com/admin/webhooks.json';	 
> 
> 		  $request_headers[0] = "X-Shopify-Access-Token: " . $token;
> 		  $request_headers[1] = "Accept: application/json";
> 		  $request_headers[2] = "Content-type: application/json";		  
> 		
> 		  //open connection
> 		  $ch = curl_init();
> 
> 		  //set the url, number of POST vars, POST data
> 		  curl_setopt($ch,CURLOPT_URL,$url);
> 		  curl_setopt($ch,CURLOPT_CUSTOMREQUEST, "POST");
> 		  curl_setopt($ch,CURLOPT_POST,count($fields_string));
> 		  curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($fields_string));
> 		  curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
> 
> 		  //execute post
> 		  $result = curl_exec($ch);
> 		  print $result;

**Comment by tareqtms** [comment]
```php
$config = array(
    'ShopUrl' => 'sub.myshopify.com',
    'AccessToken' => $token,
);

$shopify = new PHPShopify\ShopifySDK($config);

//$fields_array is the post data you are sending
$result = $shopify->Webhook->post($fields_array);
return $result;
```
