### ISSUE TITLE
Is this still being actively maintained? 

### ISSUE THREAD

**Issue by yosun** [phpclassic/php-shopify#63]
Just checking if this is still being maintained? Last update seems like it's 6 months ago

**Comment by tareqtms** [comment]
@yosun
Yes, still being maintained. Sorry that it's being late because I am too busy with some other projects. If you could send a pull request, I can merge that quickly though.

**Comment by tareqtms** [comment]
Created a build yesterday and more builds coming soon. Stay in touch.
