### ISSUE TITLE
How to get a products metafield data?

### ISSUE THREAD

**Issue by joeyc002** [phpclassic/php-shopify#64]
Shopify's documentation lists it as such:

> Retrieve a list of metafields that belong to a Product resource
> GET /admin/products/#{product_id}/metafields.json

I've tried like this, but I'm not sure on the correct way:

`$metafields = $this->shopify->Product("628755693631")->Metafield->get($params)`

Thanks.

**Comment by shawnhind** [comment]
What error do you get when you try it that way?  It looks correct to me, unless your params are incorrect.  Have you tried it without passing any params to the get method?  That should just return you all of the metafields for that product.

**Comment by joeyc002** [comment]
The method I tried gave a generic error. (I'm not at work so I can't check at the moment.)

I did try:
`$metafields = $this->shopify->Product->Metafield("628755693631");

and got an odd response, almost like it is picking up the meta data for something else completely, but it makes no sense. I'll retest tomorrow and post the results.

**Comment by joeyc002** [comment]
```
$metafields = $this->shopify->Product->Metafield(628755693631);
die(json_encode($metafields));
```

This returns 

> {"searchEnabled":false,"countEnabled":true,"readOnly":false,"id":628755693631}


```
$metafields = $this->shopify->Product("628755693631")->Metafield->get();
die(json_encode($metafields));
```

This returns

>  exception 'PHPShopify\Exception\ApiException' with message 'Not Found' in ....


"Metafield" is a child resource under "Product", but not the other way around so it has to be something like the first one, just I have no idea why I'm getting that response.

**Comment by joeyc002** [comment]
This can be closed - It was a permission error with the shop I was connecting to. I did my POSTMAN testing on a separate site.

**Comment by ortegafernando** [comment]
Hi, I have the same problem with Customer(id)->Metafield->get();

What was your problem with permission ?

I can get metafield with POSTMAN, so i dont know what is wrong here:
$data = $shopify->Customer(2229915287661)->Metafield->get();
Thanks
