### ISSUE TITLE
Class 'PHPShopify\ShopifySDK' not found error

### ISSUE THREAD

**Issue by mohan-b** [phpclassic/php-shopify#66]
I am new to php api, the below code i used under vendor folder

$config = array(
	'ShopUrl' => '*****.myshopify.com',
	'ApiKey' => '********************',
	'Password' => '*******************'
);

$shopify = new PHPShopify\ShopifySDK($config);

$productID = ######;
$product = $shopify->Product($productID)->get();
//$products = $shopify->Product->get();

var_dump($product);

where i need to place this file under which folder and how to fix this error, can you help to fix it.

**Comment by shawnhind** [comment]
Are you using composer to autoload your dependencies?

**Comment by tareqtms** [comment]
@mohan-b 
You don't need to place the file in the vendor folder. You can place it anywhere but at the top include the `vendor/autoload.php`

```
require_once 'path/to/vendor/autoload.php';

$config = array(
'ShopUrl' => '.myshopify.com',
'ApiKey' => '***************',
'Password' => '*******************'
);

$shopify = new PHPShopify\ShopifySDK($config);

$productID = ######;
$product = $shopify->Product($productID)->get();
//$products = $shopify->Product->get();

var_dump($product);
```
