### ISSUE TITLE
Strip 'path' param to validate HMAC?

### ISSUE THREAD

**Issue by kwasnicki** [phpclassic/php-shopify#70]
Writing a new shopify development app and when trying to get an accessToken I was having trouble getting the SDK to validate the HMAC.  

Seems my auth request from shopify was including a 'path' param that I didn't see in the examples.
I added this: 
  unset($_GET['path']);
before calling \PHPShopify\AuthHelper::getAccessToken()  and then everything worked fine.

Is that expected?

**Comment by tareqtms** [comment]
@kwasnicki 
As per Shopify documentation for [Oauth Verification](https://help.shopify.com/en/api/getting-started/authentication/oauth#verification), we don't have any information to remove anything except `hmac` from the query string. So we cannot do anything on this unless you can provide any official link.

**Comment by tareqtms** [comment]
@ShayneP
You have any information on this?

**Comment by ShayneP** [comment]
We don't have any other reports of this issue across the platform, the param is likely coming from somewhere inside your app. @kwasnicki, if you post on [our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology), someone from support should be able to give you a hand.

**Comment by kwasnicki** [comment]
@ShayneP You're absolutely correct, my app's (custom) framework was appending the 'path' param to the _GET input.   Thank you!
@tareqtms Thank you for digging into this and apologies that this was my own problem.  Please close this issue.  
Many thanks to you both for addressing this!
