### ISSUE TITLE
DraftOrder creation

### ISSUE THREAD

**Issue by J0ker98** [phpclassic/php-shopify#74]
Is it possible to create a DraftOrder with this SDK?

I'm trying to create a post request for a Draft Order as described in the Shopify API documentation here https://help.shopify.com/en/api/reference/orders/draftorder

But when I do

```
			$order = json_decode(
				'{
				  "draft_order": {
				    "line_items": [
				      {
				        "title": "Standard Shipping",
				        "price": "10.00",
				        "quantity": 1
				      }
				    ],
				    "note": "test order"
				  }
				}'
			, true);

			echo $shopify->DraftOrder->post($order);
```

I get the following error:

`Fatal error: Uncaught exception 'PHPShopify\Exception\SdkException' with message 'Child Resource DraftOrder is not available for Order' in /home/shopify/lib/ShopifyResource.php:171 Stack trace: #0 /home/shopify/lib/ShopifyResource.php(143): PHPShopify\ShopifyResource->__call('DraftOrder', Array) #1 /home/shopify/lib/ShopifyResource.php(143): PHPShopify\Order->DraftOrder() #2 /home/scripts/withdraw.php(125): PHPShopify\ShopifyResource->__get('DraftOrder') #3 {main} thrown in /home/shopify/lib/ShopifyResource.php on line 171`

**Comment by KiloooNL** [comment]
Is there a particular reason you are using json_decode?
The order details should be stored in array with keys (line_items, email, send_receipt etc.).
Here's an example function I use:

    function createOrder($productID, $orderDetails) {
        /**
         * Reference: OrderDetails Array
         * Array {
         *      line_items [
         *          [
         *              title:      product title
         *              variant_id: variant ID
         *              quantity:   order quantity
         *              price:      price of each item
         *
         *              inventory_behavior: decement_obeying_policy
         *          ]
         *      ]
         *      email        => email_address(string)
         *      send_receipt => boolean
         * }
         */

        // Your variable to call PHPShopify\ShopifySDK
        // EG: $shopify = new PHPShopify\ShopifySDK;
        global $shopify;

        if(is_array($orderDetails)) {
            $variantID = $orderDetails['line_items'][0]['variant_id'];

            if($shopify->Order->post($orderDetails)) {
                // Only if the order was successfully made, should we update this item's inventory level
                $currentQty = $this->getInventoryLevel($productID, $variantID);
                echo '<br><b>Item Current Quantity:</b> ' . $currentQty;

                $this->setInventoryLevel($productID, ($currentQty - $orderDetails['line_items'][0]['quantity']));
                echo '<br><b>Set new inventory level to: </b>' . ($currentQty - $orderDetails['line_items'][0]['quantity']);

                echo 'Created order in Shopify.';
            }
        } else {
            echo 'Could not make a Shopify order, as there were no order details provided.';
        }
    }

**Comment by J0ker98** [comment]
There isn’t a particular reason, I had the json string and used json_decode to encode it as array.
