### ISSUE TITLE
Using the SDK without Composer

### ISSUE THREAD

**Issue by RebootWebsites** [phpclassic/php-shopify#77]
Sorry to bother you guys but I just wanted to know the right way of require or use if you do not use composer to develop..

Would you include just the ShopifySDK.php file and use the examples of SDK usage like normal or is there a list of files to include..

**Comment by tareqtms** [comment]
@RebootWebsites 
If you don't use composer, you need to include all necessary files, that must be a list of files as per your app requirements.
