### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by stevenbrookes** [phpclassic/php-shopify#79]
Hi Tareq

Shopify are introducing API versioning - see https://help.shopify.com/en/api/versioning  How would you like to handle this. I'm happy to put a pull request together for this, but really wanted to discuss the best way to approach it.

The current version is 2019-04 so to me it makes sense to update the lib to use that version.  Then as new features or breaking changes are made by Shopify we can decide what'll take to move the library forward.

So I'd initially just update the code to use the new versioned URL and then keep an eye on changes from Shopify.  Is that OK with you?  if so I'll do a pull request for this.

Thanks

Steve

**Comment by tareqtms** [comment]
Hi Steve,

Please proceed with your updates and make a pull request when you are ready. I will review and merge as early as possible. I have a lot of other issues too to address here, not getting enough time to look into. Waiting for some free time. 

Thanks

Tareq
