### ISSUE TITLE
Orders are not creating after a limit

### ISSUE THREAD

**Issue by divyasunil** [phpclassic/php-shopify#8]
I need to add 5000 orders to shopify site.But after a particular no of order creation, it is not working.Is there any way to find the error? or any solution for this issue.I think it is related to API Rate Limit.

**Comment by tareqtms** [comment]
Shopify API has a limit with 40 calls bucket. Please read details here : https://help.shopify.com/api/getting-started/api-call-limit

However, there is a function which you can call before each call to API to maintain the time gap, when you are doing such bulk actions.

```php
ShopifySDK::checkApiCallLimit();
```

**Comment by divyasunil** [comment]
Thank you

**Comment by tareqtms** [comment]
Please close the issue, if that solves your problem.
