### ISSUE TITLE
Infinite loop after new Shopify variant creation limit

### ISSUE THREAD

**Issue by andyexeter** [phpclassic/php-shopify#81]
Shopify have introduced a limit on variant creation via API to 1000 per day for stores with over 50,000 variants: https://developers.shopify.com/changelog/api-call-limits-will-be-applied-to-variant-creation.

When this limit is reached the response code is 429 Too Many Requests. This means the following code gets caught in an infinite loop:

https://github.com/phpclassic/php-shopify/blob/d3c7f3bdfed59dd4fdcd005cef80f7bfb5d4a6c3/lib/CurlRequest.php#L141-L151

I'm not sure of the best way around this, but I'm happy to submit a PR after some feedback. We could check the response body and throw an exception to break out of the loop? The response body when this limit is hit is:

```json
{
  "errors": {
    "product": [
      "Daily variant creation limit reached. Please try again later. See https://help.shopify.com/en/api/getting-started/api-call-limit for more information about rate limits and how to avoid them."
    ]
  }
}
```

**Comment by andyexeter** [comment]
@shawnhind Thanks for the feedback. I'm aware there's no way around this other than library modification, I suggested a PR for that very reason :)

We're using the retry loop for throttling here. I already have a fork with another PR that is waiting to be merged but @tareqtms is busy at the moment.

**Comment by stadskle** [comment]
Hi,

I am having issues with this limitation as well "variant creation via API to 1000 per day for stores with over 50,000 variants". I see there is a merged PR, but it is unclear to me what it does. What is the expected behaviour of the SDK currently when this exception occurs? To me it looks like it still just goes into an infite loop?

**Comment by andyexeter** [comment]
@stadskle The PR looks for a `X-Shopify-Shop-Api-Call-Limit` header and throws an exception if one is present, thus breaking out of the infinite loop.

**Comment by stadskle** [comment]
Ok, now I see the reasoning. That makes sense, but it does not seem to work in my flow, I am getting stuck with no exception. I will add some logging to see which headers are returned frmo shopify.

In addition, I see the usleep timer is using a static value, would it not be a good idea to use the `Retry-After` header to set a dynamic sleep value?

**Comment by andyexeter** [comment]
@stadskle My latest PR (#184) uses the Retry-After value instead of a static value.
