### ISSUE TITLE
[Fixes #79] Api Versioning breaks app install - Page not found

### ISSUE THREAD

**Issue by smilga** [phpclassic/php-shopify#85]
After update from version 1.0.3 to 1.0.5, AuthHelper redirects to 
https://site.myshopify.com/admin/api/2019-04/oauth/authorize?....
That causes "The page you’re looking for could not be found" response from shopify.
Wihtout "api/2019-04/" everything works.

**Comment by tareqtms** [comment]
@smilga 
Please try with v1.0.6
