### ISSUE TITLE
Get all orders

### ISSUE THREAD

**Issue by leadstar116** [phpclassic/php-shopify#86]
I am trying to get all orders including fulfilled, cancelled, unfulfilled and so on.

$orders = $shopify->Order->get();
This returns only open orders on shopify.

**Comment by tareqtms** [comment]
```php

$params = array(
    'status' => 'any', // open / closed / cancelled / any (Default: open)
);
$orders = $shopify->Order->get($params);
```
You can see other available params from here : https://help.shopify.com/en/api/reference/orders/order#index
