### ISSUE TITLE
How to use Refund->calculate?

### ISSUE THREAD

**Issue by leadstar116** [phpclassic/php-shopify#89]
I am going to refund full order amount.
```
$shopify->Order($order_id)->Refund->calculate([
                    "currency" => "USD",
                    "shipping" => [
                        "full_refund" => true
                    ]
                ]);
```

But this returns "refund - Required parameter missing or invalid".
What should be included in parameters?
And Isn't there any full guide of your functions and parameters?

Thanks

**Comment by leadstar116** [comment]
Nobody there?
Please help me to figure this out.

Thanks.

**Comment by tareqtms** [comment]
@leadstar116 
You need to provide 'refund_line_items'. Please check the example here: https://help.shopify.com/en/api/reference/orders/refund#calculate

**Comment by leadstar116** [comment]
@tareqtms 
I've added 'refund_line_items' but get same error message.
I got line_items from order and added it to api.
Here's the data.
Array
(
    [currency] => USD
    [shipping] => Array
        (
            [full_refund] => 1
        )

    [refund_line_items] => Array
        (
            [0] => Array
                (
                    [line_item_id] => 2445464961077
                    [quantity] => 1
                    [restock_type] => no_restock
                )
        )
)

**Comment by leadstar116** [comment]
@tareqtms 
Please help me to figure this out asap.
I am stuck in this for over 3 days.
I am using your plugin for the project and it worked really great before this one.

**Comment by tareqtms** [comment]
@leadstar116 
For custom actions, you need to write full array as it is required by the API. Here you need to wrap the array with a key "refund". So try this way:
```
$shopify->Order($order_id)->Refund->calculate(["refund" => [
            "currency" => "USD",
           "shipping" => [
                 "full_refund" => true
            ]
       ] 
 ]);
```

**Comment by leadstar116** [comment]
Thanks a lot, @tareqtms 
It works.
Do I need to write full array as in API document for custom actions?
I used only contents for other apis and it worked well.

**Comment by tareqtms** [comment]
@leadstar116 
It should be same for all custom actions, since the custom actions are not given any resource key to add, can you please mention with other action you used (and you said it works)?

**Comment by leadstar116** [comment]
Yeah. it works really great.
I mainly used Products, Orders, Metafield, Images.
So now I can use this calculated refund for requesting refund, right?
Isn't there any other thing that I should know?

**Comment by tareqtms** [comment]
@leadstar116 
For Products, Orders, Metafield, Images outer array is not needed, since it will be automatically wrapped by the resource_key. So I think you are good to go. 
Please remember to close the issue. Thanks.

**Comment by leadstar116** [comment]
Thank you, @tareqtms

**Comment by leadstar116** [comment]
@tareqtms 

sorry for asking too many questions.
But i am getting another error when I try to create a refund.
```
Array
(
    [refund] => Array
        (
            [currency] => USD
            [shipping] => Array
                (
                    [full_refund] => 1
                )

            [refund_line_items] => Array
                (
                    [0] => Array
                        (
                            [line_item_id] => 2445464961077
                            [quantity] => 1
                            [restock_type] => no_restock
                        )

                )

            [transactions] => Array
                (
                    [0] => Array
                        (
                            [parent_id] => 1387421630517
                            [amount] => 48.91
                            [kind] => refund
                            [gateway] => paypal
                        )
                )
        )
)
```
$shopify->Order($order_id)->Refund->post($refund_data);

I get this error.
"error":"base - either refund line items or transactions must be present"

I don't know what's wrong.
Please help me.
Thanks.

**Comment by leadstar116** [comment]
@tareqtms

Is there something I am missing?

**Comment by leadstar116** [comment]
@tareqtms 

Could you please help me?

**Comment by tareqtms** [comment]
@leadstar116 
Please exclude "refund" from the outer array. Since this is a resource element,,it is auto handled, only custom actions are not auto handled.

**Comment by leadstar116** [comment]
yeah. it works now.
It's confusing. :-)

Thank you.
