### ISSUE TITLE
PriceRule

### ISSUE THREAD

**Issue by EkanMagnia** [phpclassic/php-shopify#9]
Hey guys.

PriceRule API is missing from your sdk. Maybe others too, but I needed this one, so here it goes:

namespace PHPShopify;

class PriceRule extends ShopifyResource {

	protected $resourceKey = 'price_rule';
}

**Comment by tareqtms** [comment]
Hi, can you please provide me the shopify reference link for this?

**Comment by kilobyte2007** [comment]
https://help.shopify.com/api/reference/discounts/pricerule

**Comment by tareqtms** [comment]
Fixed with #27
