### ISSUE TITLE
Cannot create new product

### ISSUE THREAD

**Issue by leadstar116** [phpclassic/php-shopify#95]
Hi, @tareqtms 

I am migrating over 10K products to Shopify using your SDK.
Currently, I migrated 1920 products with cron job.
It worked well for those products but suddenly API started to not working.
I've checked new product data and compared it to product which is already migrated successfully.
I couldn't find any issue in product data.
The problem is that API doesn't return any issues as well as any respond.

$shopify->Product->Post($createInfo);

Request Timeout comes here.
I am not sure this is the issue in your SDK or Shopify.
Please help me out where the main issue comes out.

Thanks.

**Comment by tareqtms** [comment]
Can you try with any REST client?

**Comment by leadstar116** [comment]
REST client? what do you mean?

**Comment by tareqtms** [comment]
There are chrome extensions to try API request directly. For example Postman. (Pls have a search in Google.)

**Comment by leadstar116** [comment]
I have a postman.
But I am not sure how to send request with shopify api keys.
That's why I am using your SDK.
Could you provide me example of creating product via REST client?

**Comment by leadstar116** [comment]
Hey, @tareqtms 

I used Postman to send request.

```
<html>
    <body>
        <noscript>
            <a href="https://app.shopify.com/services/login/identity?destination_uuid=4f92f9dc-e136-40f3-bc36-5f7fd6f5bed0&amp;return_to=https%3A%2F%2Fapp.shopify.com%2Fservices%2Flogin%2Fidentity_callback%3Fshop_name%3DillCurrency.com%26state%3DqVwzlApQBmOn-sEbqI9_zrgENnou6P6vm0NkTlfctOF46nup_SwnGWTvAooOZ-930MBC8cr1wYyC5M9SJ5N54zaqsDzean_pKafNRRGkoOYsFxyXFdq549AXwYkIarfUAeLTp5QHdmfIF6L6DbzImbfK8yPk0bA6vptCh80l28_tc1pM907yDWKsQvqyiMhHGS3WCxSNsQ-XA3MO3OMgI9baWUOYv_v5GT1fcD_3PwU%253D&amp;ui_locales=en&amp;upgradeable=false&amp;ux=shop">Continue</a>
        </noscript>
        <script type="text/javascript">
      window.location = "https:\/\/app.shopify.com\/services\/login\/identity?destination_uuid=4f92f9dc-e136-40f3-bc36-5f7fd6f5bed0\u0026return_to=https%3A%2F%2Fapp.shopify.com%2Fservices%2Flogin%2Fidentity_callback%3Fshop_name%3DillCurrency.com%26state%3DqVwzlApQBmOn-sEbqI9_zrgENnou6P6vm0NkTlfctOF46nup_SwnGWTvAooOZ-930MBC8cr1wYyC5M9SJ5N54zaqsDzean_pKafNRRGkoOYsFxyXFdq549AXwYkIarfUAeLTp5QHdmfIF6L6DbzImbfK8yPk0bA6vptCh80l28_tc1pM907yDWKsQvqyiMhHGS3WCxSNsQ-XA3MO3OMgI9baWUOYv_v5GT1fcD_3PwU%253D\u0026ui_locales=en\u0026upgradeable=false\u0026ux=shop";
    </script>
    </body>
</html>
```

But I got this respond.
I tested authorization and GET request was working successfully.
What is this respond?

**Comment by tareqtms** [comment]
Pls set the headers properly. content-type : application/json, accept: json.

**Comment by tareqtms** [comment]
Also X-Shopify-Access-Token: <Your Access Token>

**Comment by leadstar116** [comment]
https://screencast.com/t/0c8q7NjIV
Isn't this application/json header?

**Comment by leadstar116** [comment]
and I used basic auth as guide on Shopify.
It worked well for GET request.

**Comment by tareqtms** [comment]
The header seems fine. But the response shows that you have authentication issue. If it's working for GET, the possibly the account you are using doesn’thave write access. Btw, please have try with the access token option.

**Comment by leadstar116** [comment]
https://screencast.com/t/J35Ms5S3
This is body.
And how to use access token?
I copied it from Shopify but don't know where to put it.

**Comment by leadstar116** [comment]
Used here https://screencast.com/t/sjCRLjuT but not working

**Comment by tareqtms** [comment]
Set the header like you did for content-type. Name will be X-Shopify-Access-Token and value will be your token.

**Comment by leadstar116** [comment]
like this?
https://screencast.com/t/49vTDeJo0

**Comment by leadstar116** [comment]
get same error.

**Comment by leadstar116** [comment]
ah. i removed cookies and try again with token.
Got this error.
"errors": "[API] Invalid API key or access token (unrecognized login or wrong password)

**Comment by leadstar116** [comment]
token is different from secret key?

**Comment by leadstar116** [comment]
Oh, finally I found it.

"Daily variant creation limit reached. Please try again later. See https://help.shopify.com/en/api/getting-started/api-call-limit for more information about rate limits and how to avoid them."

This is the respond.
Isn't there anyway to avoid this?

**Comment by tareqtms** [comment]
This seems to be a different error than API call limit. Please use shopify forums for more help on this.

**Comment by leadstar116** [comment]
Yeah. I think there's no issue with your SDK.
I really appreciate your wonderful SDK.
Thank you for your help.

**Comment by tareqtms** [comment]
Thanks
