### ISSUE TITLE
Error 500 on setup

### ISSUE THREAD

**Issue by ngreis** [phpclassic/php-shopify#98]
```
<?php

#$chave = "xxxxxxxxxxxxxxxxxxx";
#$senha = "yyyyyyyyyyyyyyyyyyyyyyy";
#$shared_key = "zzzzzzzzzzzzzzzzzz";
#$url = "notworking.myshopify.com";

namespace PHPShopify;

use PHPShopify\ShopifySDK;

$config = array(
    'ShopUrl' => 'notworking.myshopify.com',
    'ApiKey' => 'xxxxxxxxxx',
    'Password' => 'yyyyyyyyy',
);

$shopify = new ShopifySDK($config);

$products = $shopify->Product->get();

echo $products;

?>
```

The folder structure is 

test.php
PHPShopify/files from this github (instead of lib i renamed the folder to PHPShopify).

Always getting error 500 on webpage, apache error log says:
PHP Fatal error:  Class 'PHPShopify\\ShopifySDK' not found in E:\\UniServerZ\\www\\molonify\\test.php on line 18
As the error says, i am using uniserver as a dev server and have curl installed and active.
Using PHP 5.6.

I can't wrap my head around this, some bug or error on my end, if so any help is welcomed.

Best regards

**Comment by tareqtms** [comment]
Seems like you didn’t set up composer or haven't included the autoload.php in your file

**Comment by ngreis** [comment]
Hello,

First of all, thank you for the very quick reply.

I am not using composer, was trying to load the class by hand, and getting it to work.
This is just to create a script that acesses a shopify shop to get inventory levels as a json object, every x minutes.

**Comment by tareqtms** [comment]
It is not recommended to use this library without composer. But if you are skilled enough, you can try to include all the necessary files individually to your php file. Please do whatever at your own risk. Closing the ticket since we are not eager to give support to the ways that are not recommended.
