### ISSUE TITLE
Fulfillment method issue

### ISSUE THREAD

**Issue by Jayfec** [phpclassic/php-shopify#99]
This method is not working for me. I am trying to post a simple fulfillment and I get following response back from Shopify. I used post man to send the same payload and it works just fine.

["error"]=>
  string(57) "location_id must be specified when creating fulfillments."

**Method**
` $this->shopify->Order($order_id)->Fulfillment->post($data);`

**Payload**
```
$updateInfo = array (
    'fulfillment' => array(
        "location_id" => $location_id,
        "tracking_number" => "123456789",
    )
);
```

Anyone experiencing this issue?

**Comment by Jayfec** [comment]
I figured this out and it amounts to user error.

The proper payload would look something like 
```
$updateInfo = array (
    "location_id" => 32403587132,
    "tracking_number" => "123456789",
);
```
Note that the 'fulfillment' is added automatically through the method.

**Comment by trantuanngoctn97** [comment]
Hi guys, Can i update a Fulfillment by using method put ?
I want to update tracking_number in fulfillments object. I use postman for test. In the first call, its work. But in the second call, its say `order - is already fulfilled` . Please help me how to update a fulfillments ?
Thank you in advance.

**Comment by Jayfec** [comment]
You should have no issue using PUT. See [here](https://help.shopify.com/en/api/reference/shipping-and-fulfillment/fulfillment#update-2019-04)

$this->shopify->Order($order_id)->Fulfillment->put($data);

**Comment by trantuanngoctn97** [comment]
> You should have no issue using PUT. See [here](https://help.shopify.com/en/api/reference/shipping-and-fulfillment/fulfillment#update-2019-04)
> 
> $this->shopify->Order($order_id)->Fulfillment->put($data);

I tried. But its not work.
Its say: 
````
Type: PHPShopify\Exception\CurlException
Message: Request failed with HTTP Code 406.
````
How should i do ?

**Comment by trantuanngoctn97** [comment]
POST only work in the first time, **fulfillments** is added automatically through this method. From the second time, its say: `order - is already fulfilled`. 
I can't use PUT() like you see.
SET() is not work too. its say: `No action named set is defined for Fulfillment`.

I also make an issue on this repository. Could you help me ?
